'use strict';
function setMove(u,x,y,mode='move'){if(u.dead)return;u.path=findPath(u.x,u.y,x,y);u.pathIndex=0;u.order={type:mode,x,y};u.carrying=null}
    function setAttack(u,target){if(u.dead||!target||target.dead)return;u.order={type:'attack',targetId:target.id};u.path=[];u.pathIndex=0}
    function setGather(u,target){if(u.type!=='villager'||!target)return;u.order={type:'gather',targetId:target.id};u.path=findPath(u.x,u.y,target.x,target.y);u.pathIndex=0}
    function setBuild(u,target){if(u.type!=='villager'||!target)return;u.order={type:'build',targetId:target.id};u.path=findPath(u.x,u.y,target.x,target.y);u.pathIndex=0}
    function stopUnit(u){u.order={type:'idle'};u.path=[];u.pathIndex=0}
    const WORK_ACTIVITY=Object.freeze({
      wood:{label:'伐木中',short:'木',color:'#9fd071'},food:{label:'採集食物',short:'食',color:'#e7a86c'},
      gold:{label:'開採黃金',short:'金',color:'#f0c75c'},stone:{label:'開採石材',short:'石',color:'#bec9cc'},
      build:{label:'建造中',short:'築',color:'#e1b978'}
    });
    function unitActivityState(u){
      const order=u?.order||{type:'idle'},moving=!!u?.path?.length,target=Number.isFinite(order.targetId)?entityById(order.targetId):null;
      if(order.type==='gather'){
        const resource=target?.kind==='resource'?target.type:target?.type==='farm'?'food':'food',meta=WORK_ACTIVITY[resource]||WORK_ACTIVITY.food,reach=(target?.radius||0)+(u?.radius||0)+6;
        return{kind:'gather',resource,target,moving,active:!!target&&!moving&&dist(u,target)<=reach+2,...meta,label:moving?`前往${meta.label.replace('中','')}`:meta.label};
      }
      if(order.type==='build'){
        const meta=WORK_ACTIVITY.build,reach=(target?.radius||0)+(u?.radius||0)+5;
        return{kind:'build',target,moving,active:!!target&&!moving&&target.construction<1&&dist(u,target)<=reach+2,...meta,label:moving?'前往工地':meta.label};
      }
      if(order.type==='attack')return{kind:'attack',target,moving,active:!!target&&!moving,label:moving?'追擊中':'交戰中',short:'戰',color:'#f07d70'};
      if(order.type==='move'||order.type==='attackMove')return{kind:order.type,target:null,moving,active:moving,label:order.type==='attackMove'?'進軍中':'移動中',short:order.type==='attackMove'?'攻':'行',color:'#78c8d8'};
      return{kind:'idle',target:null,moving:false,active:false,label:'待命',short:'待',color:'#a8b4b7'};
    }
    function buildingProgressStates(b){
      const states=[];
      if(!b||b.dead)return states;
      if(b.construction<1)states.push({kind:'construction',ratio:clamp(b.construction,0,1),label:'興建中',color:'#d9b36c'});
      if(b.queue?.length){const q=b.queue[0],name=UNIT[q.type]?.name||'單位',total=Math.max(1,Number(q.total)||Number(q.remaining)||1);states.push({kind:'training',ratio:clamp(1-(Number(q.remaining)||0)/total,0,1),label:`訓練${name}`,color:'#71c7d7'})}
      const p=playerFor(b.faction);
      if(b.type==='town'&&p?.ageUp){const total=Math.max(1,Number(p.ageUp.total)||Number(p.ageUp.remaining)||1);states.push({kind:'age',ratio:clamp(1-(Number(p.ageUp.remaining)||0)/total,0,1),label:`晉升${AGES[p.age]}`,color:'#f1d06e'})}
      if(b.type==='wonder'&&b.construction>=1&&b.wonderTimer<180)states.push({kind:'wonder',ratio:clamp(b.wonderTimer/180,0,1),label:'奇觀倒數',color:'#edc65c'});
      return states;
    }
    function siteProgressState(s){
      if(!s)return null;if(s.contested)return{kind:'contested',ratio:clamp(s.progress/6,0,1),label:'爭奪中',color:'#f07d70'};
      if(s.captureBy>=0&&s.progress<6)return{kind:'capture',ratio:clamp(s.progress/6,0,1),label:'佔領中',color:FACTION_COLORS[s.captureBy]||'#e6c66d'};
      return null;
    }
    function moveToward(u,tx,ty,dt,speedMul=1){
      const dx=tx-u.x,dy=ty-u.y,d=Math.hypot(dx,dy);if(d<2)return true;let speed=u.speed*speedMul;
      if(powerActive(u.faction))speed*=roleModifier(powerMods(u.faction).unitSpeed,UNIT[u.type],u.type,1);
      const step=Math.min(d,speed*dt);u.angle=Math.atan2(dy,dx);let nx=u.x+dx/d*step,ny=u.y+dy/d*step;
      if(!isLandPx(nx,ny)){const alt=findPath(u.x,u.y,tx,ty);if(alt.length){u.path=alt;u.pathIndex=0}return false}
      let sx=0,sy=0;for(const o of game.entities){if(o===u||o.dead||o.kind!=='unit'||Math.abs(o.x-u.x)>32||Math.abs(o.y-u.y)>32)continue;const odx=u.x-o.x,ody=u.y-o.y,od=Math.hypot(odx,ody)||1,min=u.radius+o.radius;if(od<min){sx+=odx/od*(min-od)*.18;sy+=ody/od*(min-od)*.18}}
      u.x=clamp(nx+sx,8,WORLD_W-8);u.y=clamp(ny+sy,8,WORLD_H-8);return step>=d-.5
    }
    function followPath(u,dt){if(!u.path?.length)return true;const p=u.path[u.pathIndex];if(moveToward(u,p.x,p.y,dt)){u.pathIndex++;if(u.pathIndex>=u.path.length){u.path=[];return true}}return false}
    function nearestEnemy(u,range=190){let best=null,bd=range;for(const e of game.entities){if(e.dead||e.faction===u.faction||e.construction<1)continue;const d=dist(u,e)-e.radius;if(d<bd){bd=d;best=e}}return best}
    function nearestResource(u,type=null){let best=null,bd=1e9;for(const n of game.nodes){if(n.dead||n.amount<=0||(type&&n.type!==type))continue;const d=dist(u,n);if(d<bd){bd=d;best=n}}for(const b of game.entities){if(b.dead||b.kind!=='building'||b.type!=='farm'||b.faction!==u.faction||b.food<=0||b.construction<1)continue;const d=dist(u,b);if(d<bd){bd=d;best=b}}return best}
    function economicBuildingBonus(u,type,target){const required=type==='food'?'mill':type==='wood'?'lumber':null;if(!required)return 1;return game.entities.some(e=>!e.dead&&e.faction===u.faction&&e.kind==='building'&&e.type===required&&e.construction>=1&&dist(e,target)<=190)?1.1:1}
    function unitRole(t){if(t.kind==='building')return'building';const d=UNIT[t.type];return d.role||t.type}
    function effectiveArmor(target){const d=UNIT[target.type],bonus=target.kind==='unit'?roleModifier(powerMods(target.faction).unitArmor,d,target.type,0):0;return(target.armor||0)+bonus}
    function attackDamage(u,target){const d=UNIT[u.type],p=playerFor(u.faction);let val=(u.damage+p.tech.attack)*roleModifier(powerMods(u.faction).unitDamage,d,u.type,1);const role=unitRole(target);if(d.bonus){val+=d.bonus[role]||0;val+=d.bonus[target.type]||0}return Math.max(1,Math.round(val-effectiveArmor(target)))}
    function damageReduction(target){const reduction=target.kind==='building'?(powerMods(target.faction).buildingReduction||0):0;return clamp(1-reduction,.1,1)}
    function applyDamage(target,amount,source){if(!target||target.dead)return;amount=Math.max(1,amount*damageReduction(target));target.hp-=amount;target.flash=.12;target.lastHit=game.time;spawnFloat(target.x,target.y-target.radius-7,`−${Math.round(amount)}`,'#ffd1c8');if(target.faction===0&&game.time-(game.lastAlert||-20)>8){game.lastAlert=game.time;notify('我方正遭受攻擊！','danger');Audio.sfx('alert')}if(target.hp<=0)destroyEntity(target,source)}
    function destroyEntity(e,killer){if(e.dead)return;e.dead=true;if(e.kind==='unit'){const p=playerFor(e.faction);p.pop=Math.max(0,p.pop-UNIT[e.type].pop);p.losses++;if(killer)playerFor(killer.faction).kills++}else{const d=BUILD[e.type],p=playerFor(e.faction);if(d.pop)p.popCap=Math.max(0,p.popCap-d.pop);if(e.type==='town'){p.eliminated=true;if(e.faction===0)endGame(false,'征服');else{for(const o of game.entities)if(o!==e&&o.faction===e.faction)o.dead=true;p.pop=0;for(const s of game.sites)if(s.owner===e.faction){s.owner=-1;s.progress=0;s.captureBy=-1}notify(`第 ${e.faction+1} 勢力已退出戰局。`,'good');if(game.players.slice(1).every(q=>q.eliminated))endGame(true,'征服')}}if(e.type==='wonder')game.wonder[e.faction]=0}burst(e.x,e.y,FACTION_COLORS[e.faction]||'#e9675e',e.kind==='building'?28:10);Audio.sfx(e.kind==='building'?'siege':'sword')}
    function launchProjectile(u,target,damage){const d=UNIT[u.type],siege=d.role==='siege',totalDist=Math.max(1,dist(u,target));game.projectiles.push({x:u.x,y:u.y,tx:target.x,ty:target.y,startX:u.x,startY:u.y,totalDist,traveled:0,targetId:target.id,damage,sourceId:u.id,speed:siege?250:480,color:siege?'#bda77b':'#f0d394',siege,splash:d.splash||0,dead:false});Audio.sfx(siege?'siege':'arrow')}
    function performAttack(u,target){const d=UNIT[u.type],damage=attackDamage(u,target),ranged=u.range>50||d.ranged;if(ranged)launchProjectile(u,target,damage);else{applyDamage(target,damage,u);Audio.sfx(d.role==='siege'?'siege':'sword');burst(target.x,target.y,'#e6c48b',4)}u.attackTimer=u.cool*roleModifier(powerMods(u.faction).unitCooldown,d,u.type,1)}
    function updateUnit(u,dt){
      u.prevX=u.x;u.prevY=u.y;u.anim+=dt*(2+u.speed/40);u.attackTimer-=dt;u.flash=Math.max(0,u.flash-dt);u.scanTimer=(u.scanTimer||0)-dt;
      const d=UNIT[u.type],o=u.order||{type:'idle'};
      if(d.regen&&u.hp<u.maxHp&&game.time-(u.lastHit??-99)>4)u.hp=Math.min(u.maxHp,u.hp+d.regen*dt);
      if(o.type==='move'||o.type==='attackMove'){const done=followPath(u,dt);if(o.type==='attackMove'&&u.scanTimer<=0){u.scanTimer=.35;const sight=Math.max(210,u.range*roleModifier(powerMods(u.faction).unitRange,d,u.type,1)+55),foe=nearestEnemy(u,sight);if(foe){setAttack(u,foe);return}}if(done)stopUnit(u)}
      else if(o.type==='attack'){const t=entityById(o.targetId);if(!t||t.dead){stopUnit(u);return}const boostedRange=u.range*roleModifier(powerMods(u.faction).unitRange,d,u.type,1),range=boostedRange+(boostedRange>50?t.radius:u.radius+t.radius),dd=dist(u,t);if(dd>range){if(!u.path.length||u.pathIndex>=u.path.length)u.path=findPath(u.x,u.y,t.x,t.y),u.pathIndex=0;followPath(u,dt)}else{u.angle=Math.atan2(t.y-u.y,t.x-u.x);if(u.attackTimer<=0)performAttack(u,t)}}
      else if(o.type==='gather'){const t=entityById(o.targetId);if(!t||t.dead||(t.amount!==undefined&&t.amount<=0)||(t.type==='farm'&&t.food<=0)){stopUnit(u);return}const reach=t.radius+u.radius+6;if(dist(u,t)>reach){if(!u.path.length)u.path=findPath(u.x,u.y,t.x,t.y),u.pathIndex=0;followPath(u,dt)}else{u.path=[];u.angle=Math.atan2(t.y-u.y,t.x-u.x);u.workTimer+=dt;const type=t.kind==='resource'?t.type:'food',p=playerFor(u.faction),passive=civMods(p.civ).gather||{},active=powerMods(u.faction).gather||{};let rate={food:.7,wood:.65,gold:.55,stone:.45}[type];rate*=1+p.tech.economy*.1;rate*=passive[type]??passive.all??1;rate*=active[type]??active.all??1;rate*=economicBuildingBonus(u,type,t);const gain=rate*dt;p.res[type]+=gain;if(!u.faction)game.stats.gathered+=gain;if(t.kind==='resource'){t.amount-=gain;if(t.amount<=0){t.dead=true;burst(t.x,t.y,'#9d885d',7)}}else t.food-=gain;if(u.workTimer>.7){u.workTimer=0;spawnParticle(t.x+(rnd()-.5)*12,t.y-5,type==='wood'?'#b6cf84':type==='gold'?'#f4c75e':type==='stone'?'#b8c2c5':'#d98e5d',2)}}}
      else if(o.type==='build'){const b=entityById(o.targetId);if(!b||b.dead||b.construction>=1){stopUnit(u);return}if(dist(u,b)>b.radius+u.radius+5){if(!u.path.length)u.path=findPath(u.x,u.y,b.x,b.y),u.pathIndex=0;followPath(u,dt)}else{u.path=[];u.angle=Math.atan2(b.y-u.y,b.x-u.x);const p=playerFor(u.faction),rate=(1/b.buildTime)*(civMods(p.civ).buildSpeed||1)*(powerMods(u.faction).buildSpeed||1),prev=b.construction;b.construction=Math.min(1,b.construction+rate*dt);b.hp=Math.max(b.hp,b.maxHp*b.construction);if(u.workTimer<=0){u.workTimer=.45;spawnParticle(b.x+(rnd()-.5)*b.radius,b.y+(rnd()-.5)*10,'#cbb58a',3);Audio.sfx('build')}u.workTimer-=dt;if(prev<1&&b.construction>=1)finishBuilding(b)}}
      else if(o.type==='idle'&&d.role!=='worker'&&u.scanTimer<=0){u.scanTimer=.55+rnd()*.2;const sight=Math.max(165,u.range*roleModifier(powerMods(u.faction).unitRange,d,u.type,1)+45),foe=nearestEnemy(u,sight);if(foe)setAttack(u,foe)}
    }
    function finishBuilding(b){const d=BUILD[b.type],p=playerFor(b.faction);if(d.pop)p.popCap=Math.min(MAX_POP,p.popCap+d.pop);burst(b.x,b.y,'#e3c36e',16);if(!b.faction){game.stats.built++;notify(`${d.name}已完工。`,'good');tutorialEvent('built',b.type)}Audio.sfx('age')}
    function queuedPopulation(p){let n=0;for(const b of game.entities)if(!b.dead&&b.faction===p.faction&&b.queue)for(const q of b.queue)n+=UNIT[q.type]?.pop||0;return n}
    function queueUnit(b,type,silent=false){const p=playerFor(b.faction),d=UNIT[type];if(!d||b.construction<1||p.age<d.age)return false;if(d.unique&&d.unique!==p.civ)return false;const allowed=[...(TRAIN_AT[b.type]||[])];if(CIVS[p.civ].unique===type&&(d.trainAt===b.type||(!d.trainAt&&((b.type==='range'&&d.role==='ranged')||(b.type==='stable'&&d.role==='cavalry')||(b.type==='barracks'&&d.role==='infantry')))))allowed.push(type);if(!allowed.includes(type))return false;if(p.pop+queuedPopulation(p)+d.pop>Math.min(MAX_POP,p.popCap)){if(!silent)toast('人口已滿，請興建房舍。');return false}const cost=civAdjustedCost(d,p.civ);if(!spend(p,cost)){if(!silent)toast('資源不足。');return false}const time=d.time/roleModifier(civMods(p.civ).trainSpeed,d,type,1);b.queue.push({type,remaining:time,total:time});if(!silent){Audio.sfx('click');tutorialEvent('trainQueued',type)}return true}
    function updateBuilding(b,dt){
      b.flash=Math.max(0,b.flash-dt);b.activityFlash=Math.max(0,(b.activityFlash||0)-dt);if(b.construction<1)return;const p=playerFor(b.faction),d=BUILD[b.type];
      if(b.queue.length){const q=b.queue[0];q.remaining-=dt;if(q.remaining<=0){const a=rnd()*Math.PI*2,x=b.rally.x+Math.cos(a)*12,y=b.rally.y+Math.sin(a)*12;const u=createUnit(q.type,b.faction,x,y);b.queue.shift();b.activityFlash=.7;burst(b.x,b.y,'#e6c66d',8);if(!b.faction){game.stats.trained++;notify(`${UNIT[q.type].name}已完成訓練。`,'good')}setMove(u,b.rally.x,b.rally.y)}}
      if(d.attack){b.attackTimer-=dt;const range=d.range*(civMods(p.civ).towerRange||1);if(b.attackTimer<=0){const t=nearestEnemy(b,range);if(t){const fake={...b,type:'archer',damage:d.attack,range,cool:d.cool,armor:0};launchProjectile(fake,t,Math.max(1,d.attack-effectiveArmor(t)));b.attackTimer=d.cool}}}
      if(b.type==='wonder'){b.wonderTimer+=dt;game.wonder[b.faction]=b.wonderTimer;if(b.wonderTimer>=180)endGame(b.faction===0,'奇觀')}
    }
    function updateProjectiles(dt){for(const p of game.projectiles){if(p.dead)continue;const t=entityById(p.targetId);if(t&&!t.dead){p.tx=t.x;p.ty=t.y}const dx=p.tx-p.x,dy=p.ty-p.y,d=Math.hypot(dx,dy),step=p.speed*dt;if(d<=step+4){p.dead=true;const src=entityById(p.sourceId);if(p.splash){for(const e of game.entities)if(!e.dead&&src&&e.faction!==src.faction&&dist(e,{x:p.tx,y:p.ty})<p.splash)applyDamage(e,p.damage*(e.id===p.targetId?1:.55),src)}else if(t&&!t.dead)applyDamage(t,p.damage,src);burst(p.tx,p.ty,p.siege?'#d1b081':'#e9d49b',p.siege?13:4)}else{p.x+=dx/d*step;p.y+=dy/d*step;p.traveled=(p.traveled||0)+step}}game.projectiles=game.projectiles.filter(p=>!p.dead)}
    function updateSites(dt){
      const count=game.players.length;
      for(const s of game.sites){const has=Array(count).fill(0);for(const u of game.entities)if(!u.dead&&u.kind==='unit'&&UNIT[u.type].role!=='worker'&&dist(u,s)<112)has[u.faction]++;
        if(s.owner>=0&&!playerFor(s.owner)?.eliminated)playerFor(s.owner).res.gold+=.4*dt;const present=has.map((n,f)=>n?f:-1).filter(f=>f>=0);s.contested=present.length>1;if(s.contested)continue;if(present.length!==1){if(s.progress<6){s.captureBy=-1;s.progress=Math.max(0,s.progress-dt*.8)}continue}const f=present[0];if(s.captureBy!==f){s.captureBy=f;s.progress=Math.max(0,s.owner===f?6:0)}s.progress+=dt;if(s.progress>=6&&s.owner!==f){s.owner=f;s.progress=6;burst(s.x,s.y,FACTION_COLORS[f]||'#e6c66d',16);notify(`${f===0?'我軍':`第 ${f+1} 勢力`}奪下${s.label}。`,f===0?'good':'danger');if(f===0)tutorialEvent('site');Audio.sfx(f===0?'age':'alert')}
      }
      for(let f=0;f<count;f++){if(game.sites.every(s=>s.owner===f))game.supremacy[f]+=dt;else game.supremacy[f]=Math.max(0,game.supremacy[f]-dt*2);if(game.supremacy[f]>=90)endGame(f===0,'霸權')}
    }
    function updateAge(p,dt){if(!p.ageUp)return;p.ageUp.remaining-=dt;if(p.ageUp.remaining<=0){p.age=p.ageUp.to;p.ageUp=null;for(const b of game.entities)if(!b.dead&&b.faction===p.faction&&b.type==='town'){b.maxHp=Math.round(b.maxHp*1.22);b.hp=Math.min(b.maxHp,b.hp+b.maxHp*.22);b.activityFlash=1;burst(b.x,b.y,'#f1d06e',18)}if(p.faction===0){notify(`帝國邁入${AGES[p.age-1]}！`,'good');tutorialEvent('aged');Audio.sfx('age')}}}
    function beginAgeUp(p){if(p.age>=4||p.ageUp)return;const req=ageRequirement(p);if(!req.met){if(!p.faction)toast(req.text);return}const cost=ageCost(p);if(!spend(p,cost)){toast('晉升時代所需資源不足。');return}const time=[0,40,55,70][p.age];p.ageUp={to:p.age+1,remaining:time,total:time};if(p.faction===0)tutorialEvent('ageQueued');notify(`正在籌備晉升${AGES[p.age]}。`);Audio.sfx('click')}
    function usePower(faction=0){const p=playerFor(faction);if(!p||p.eliminated)return;if(p.age<2){if(!faction)toast('文明軍令於封建時代解鎖。');return}if((p.powerReady||0)>game.time){if(!faction)toast(`軍令尚需 ${Math.ceil(p.powerReady-game.time)} 秒。`);return}const mods=CIVS[p.civ].powerMods||{},dur=mods.duration||12;p.powerReady=game.time+120;p.powerUntil=game.time+dur;if(mods.reveal&&faction===0)game.revealUntil=game.time+dur;if(mods.heal)for(const u of game.entities){if(u.dead||u.faction!==faction||u.kind!=='unit')continue;const ratio=roleModifier(mods.heal,UNIT[u.type],u.type,0);if(ratio>0)u.hp=Math.min(u.maxHp,u.hp+u.maxHp*ratio)}notify(`${faction?`第 ${faction+1} 勢力`:'我軍'}發動「${CIVS[p.civ].power}」！`,faction?'danger':'good');if(!faction)tutorialEvent('power');Audio.sfx('power')}
    function chooseCounterUnit(faction,opts,skill){if(!opts.length)return null;const hostile=game.entities.filter(e=>!e.dead&&e.faction!==faction&&e.kind==='unit'),roles={infantry:0,ranged:0,cavalry:0,siege:0};for(const e of hostile)roles[UNIT[e.type].role]=(roles[UNIT[e.type].role]||0)+1;if(rnd()>skill)return opts[Math.floor(rnd()*opts.length)];const desired=roles.cavalry>=Math.max(roles.ranged,roles.infantry)?'spear':roles.ranged>=roles.infantry?'cavalry':'archer';return opts.find(t=>t===desired)||opts[Math.floor(rnd()*opts.length)]}
    function tryAIAge(p,to,earliest){if(p.age!==to-1||p.ageUp||game.time<earliest||!ageRequirement(p).met)return;const cost=ageCost(p);if(spend(p,cost)){const total=[0,40,55,70][p.age]*.82;p.ageUp={to,remaining:total,total}}}
    function updateAI(dt){
      const cfg=DIFF[game.difficulty],tutorialLocked=game.tutorial?.active&&!game.tutorial.completed&&(game.tutorial.step||0)<11;
      for(let faction=1;faction<game.players.length;faction++){const p=playerFor(faction),ai=game.ais?.[faction];if(!p||!ai||p.eliminated)continue;const rate=cfg.aiRate;for(const k of Object.keys(p.res))p.res[k]+=cfg.income*rate*dt;
        ai.think-=dt;ai.wave-=dt;ai.build-=dt;ai.train-=dt;if(ai.think>0)continue;ai.think=cfg.think*(.9+rnd()*.22);
        for(const u of game.entities)if(!u.dead&&u.faction===faction&&u.type==='villager'&&u.order.type==='idle'){const prefer=['wood','food','gold','stone'][u.id%4],n=nearestResource(u,prefer)||nearestResource(u);if(n)setGather(u,n)}
        tryAIAge(p,2,95/rate);tryAIAge(p,3,275/rate);tryAIAge(p,4,610/rate);
        const alive=type=>game.entities.filter(e=>!e.dead&&e.faction===faction&&e.kind==='building'&&e.type===type),base=game.spawn[faction];
        if(ai.build<=0){ai.build=13/rate;let type=null;if(p.popCap-p.pop<8)type='house';else if(!alive('mill').length)type='mill';else if(!alive('lumber').length)type='lumber';else if(!alive('barracks').length)type='barracks';else if(p.age>=2&&!alive('blacksmith').length)type='blacksmith';else if(p.age>=2&&!alive('range').length)type='range';else if(p.age>=2&&!alive('stable').length)type='stable';else if(p.age>=3&&!alive('castle').length)type='castle';else if(p.age>=3&&!alive('workshop').length)type='workshop';else if(p.age>=2&&alive('tower').length<2)type='tower';const buildDef=type?{...BUILD[type],key:type}:null,cost=buildDef?civAdjustedCost(buildDef,p.civ):null;if(type&&canAfford(p,cost)){for(let tries=0;tries<8;tries++){const a=rnd()*Math.PI*2,r=140+rnd()*150,x=base.x+Math.cos(a)*r,y=base.y+Math.sin(a)*r;if(isLandPx(x,y)&&validBuildAt(type,x,y)){spend(p,cost);const b=createBuilding(type,faction,x,y,0),worker=game.entities.find(e=>!e.dead&&e.faction===faction&&e.type==='villager');if(worker)setBuild(worker,b);break}}}}
        if(ai.train<=0){ai.train=3.2/rate;const buildings=game.entities.filter(e=>!e.dead&&e.faction===faction&&e.kind==='building'&&e.construction>=1&&e.queue.length<2);for(const b of buildings){let opts=(TRAIN_AT[b.type]||[]).filter(t=>UNIT[t].age<=p.age);const uq=CIVS[p.civ].unique,ud=UNIT[uq];if(ud&&(ud.trainAt===b.type||(!ud.trainAt&&((b.type==='range'&&ud.role==='ranged')||(b.type==='stable'&&ud.role==='cavalry')||(b.type==='barracks'&&ud.role==='infantry')))))opts.push(uq);const pick=chooseCounterUnit(faction,opts,cfg.counter);if(pick&&p.pop+queuedPopulation(p)<p.popCap)queueUnit(b,pick,true)}}
        if(ai.wave<=0){ai.wave=cfg.wave*(.82+rnd()*.35);if(tutorialLocked)continue;const army=game.entities.filter(e=>!e.dead&&e.faction===faction&&e.kind==='unit'&&UNIT[e.type].role!=='worker');if(army.length>=5){const hostileTowns=game.entities.filter(e=>!e.dead&&e.faction!==faction&&e.type==='town'),target=rnd()<.28?game.sites[Math.floor(rnd()*game.sites.length)]:hostileTowns.sort((a,b)=>dist(base,a)-dist(base,b))[0];if(target){for(const u of army)setAttack(u,target);if(target.faction===0||target.type==='town'&&target.faction===0){notify(`第 ${faction+1} 勢力集結 ${army.length} 名戰士向我方推進！`,'danger');Audio.sfx('alert')}usePower(faction)}}}
      }
    }
    function updateFog(force=false){game.fogTimer-=force?99:STEP;if(game.fogTimer>0)return;game.fogTimer=.32;for(let i=0;i<game.fog.length;i++)if(game.fog[i]===2)game.fog[i]=1;if(game.revealUntil>game.time){game.fog.fill(2);return}for(const e of game.entities){if(e.dead||e.faction!==0)continue;const sight=e.kind==='building'?190:(UNIT[e.type].sight||230),cx=(e.x/TILE)|0,cy=(e.y/TILE)|0,r=Math.ceil(sight/TILE);for(let y=cy-r;y<=cy+r;y++)for(let x=cx-r;x<=cx+r;x++)if(x>=0&&y>=0&&x<MAP_W&&y<MAP_H&&Math.hypot(x-cx,y-cy)<=r)game.fog[y*MAP_W+x]=2}}
    function cleanup(){for(const e of game.entities)if(e.dead)game.selected.delete(e.id);game.entities=game.entities.filter(e=>!e.dead);game.nodes=game.nodes.filter(n=>!n.dead);game.projectiles=game.projectiles.filter(p=>!p.dead);game.particles=game.particles.filter(p=>p.life>0);game.markers=game.markers.filter(m=>m.life>0)}
    function updateGame(dt){
      if(!game||game.paused||game.ended)return;game.time+=dt;game.tick++;game.combat=Math.max(0,game.combat-dt*.25);for(const p of game.players)if(!p.eliminated)updateAge(p,dt);
      for(const e of game.entities){if(e.dead)continue;e.kind==='unit'?updateUnit(e,dt):updateBuilding(e,dt)}updateProjectiles(dt);updateSites(dt);updateAI(dt);updateFog();
      for(const p of game.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=18*dt;p.life-=dt}for(const m of game.markers)m.life-=dt;updateTutorial(dt);
      game.autoSaveIn=(game.autoSaveIn??30)-dt;if(game.autoSaveIn<=0){game.autoSaveIn=30;persistGame(true)}
      if(game.tick%15===0)cleanup();if(game.tick%6===0)updateHUD();
    }
    function endGame(playerWon,way){if(!game||game.ended)return;game.ended=true;game.paused=true;const won=!!playerWon;$('#endMedal').textContent=won?'勝':'敗';$('#endTitle').textContent=won?'帝國凱旋':'山河失守';$('#endSummary').textContent=`${won?'你以':'敵軍以'}「${way}」奪得勝利 · 戰局 ${formatTime(game.time)} · 擊破 ${game.player.kills} · 折損 ${game.player.losses}`;$('#endOverlay').classList.remove('hidden');Audio.sfx(won?'win':'lose')}
