'use strict';
const SAVE_KEY='帝國餘燼_戰局_v4',V3_SAVE_KEY='帝國餘燼_戰局_v3',V2_SAVE_KEY='帝國餘燼_戰局_v2',LEGACY_SAVE_KEY='帝國餘燼_戰局',PREFS_KEY='帝國餘燼_設定',TUTORIAL_DONE_KEY='帝國餘燼_教學完成',CURRENT_PROJECTION='topdown-v1';
const LEGACY_CIV_MAP={jade:'chinese',steppe:'mongols',desert:'saracens',north:'teutons',isles:'vikings',jungle:'goths',iron:'franks',peacock:'persians',assyrians:'mongols',babylonians:'byzantines',carthaginians:'goths',choson:'japanese',egyptians:'saracens',greeks:'byzantines',hittites:'turks',macedonians:'franks',minoans:'britons',palmyrans:'saracens',phoenicians:'vikings',romans:'teutons',shang:'chinese',sumerians:'goths',yamato:'japanese'};
const LEGACY_UNIT_MAP={repeater:'chuKoNu',horseArcher:'mangudai',camel:'mameluke',axeguard:'teutonicKnight',windRanger:'berserk',eagle:'huskarl',elephant:'warElephant',assyrianChariot:'mangudai',babylonianGuard:'cataphract',sacredBand:'huskarl',chosonGuard:'samurai',egyptianChariot:'mameluke',greekHoplite:'cataphract',hittiteChariot:'janissary',companion:'throwingAxeman',cretanArcher:'longbowman',palmyranCamel:'mameluke',immortal:'warElephant',phoenicianElephant:'berserk',legion:'teutonicKnight',shangHalberd:'chuKoNu',sumerianChariot:'huskarl',yamatoRider:'samurai'};
   function storedSaveRaw(){try{return localStorage.getItem(SAVE_KEY)||localStorage.getItem(V3_SAVE_KEY)||localStorage.getItem(V2_SAVE_KEY)||localStorage.getItem(LEGACY_SAVE_KEY)}catch{return null}}
function hasPersistentSave(){return!!storedSaveRaw()}
function tutorialWasCompleted(){try{return!!localStorage.getItem(TUTORIAL_DONE_KEY)}catch{return false}}
   function loadPreferences(){try{const p=JSON.parse(localStorage.getItem(PREFS_KEY)||'null');if(!p)return;const civ=LEGACY_CIV_MAP[p.civ]||p.civ;if(CIVS[civ])chosenCiv=civ;if(DIFF[p.difficulty])difficulty=p.difficulty;if([2,3,4].includes(p.playerCount))playerCount=p.playerCount;if(Number.isFinite(p.volume))Audio.volume=clamp(p.volume,0,1);Audio.muted=!!p.muted;if(typeof p.reducedMotion==='boolean')reducedMotion=p.reducedMotion}catch{}}
function savePreferences(){try{localStorage.setItem(PREFS_KEY,JSON.stringify({civ:chosenCiv,difficulty,playerCount,volume:Audio.volume,muted:Audio.muted,reducedMotion}))}catch{}}
function formatTime(t){const m=Math.floor(t/60),s=Math.floor(t%60);return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
    let toastTimer=0;
    function toast(msg){dom.toast.textContent=msg;dom.toast.classList.add('show');dom.aria.textContent=msg;clearTimeout(toastTimer);toastTimer=setTimeout(()=>dom.toast.classList.remove('show'),1800)}
    function notify(msg,type=''){const el=document.createElement('div');el.className=`notice ${type}`;el.textContent=msg;dom.notices.prepend(el);while(dom.notices.children.length>3)dom.notices.lastElementChild.remove();setTimeout(()=>{el.style.opacity='0';setTimeout(()=>el.remove(),250)},6200)}
    function renderMenuState(){
      $('#civCards').innerHTML=Object.entries(CIVS).map(([key,c])=>`<button type="button" class="civ-card ${chosenCiv===key?'active':''}" data-civ="${key}" style="color:${c.color}" aria-pressed="${chosenCiv===key}"><span class="civ-head"><span class="civ-seal">${c.seal}</span><span><h2>${c.name}</h2><span class="civ-style">${c.style}</span></span></span>${c.pros.map(t=>`<span class="trait pro">${t}</span>`).join('')}<span class="trait con">${c.cons[0]}</span><span class="civ-power">軍令｜${c.power}：${c.powerDesc}</span></button>`).join('');
      $$('[data-diff]').forEach(b=>{const active=b.dataset.diff===difficulty;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});$$('[data-players]').forEach(b=>{const active=Number(b.dataset.players)===playerCount;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});
      $('#matchHint').textContent=`${difficulty} · ${playerCount} 方混戰：${DIFF[difficulty].desc}`;
      $('#tutorialBtn').textContent=tutorialWasCompleted()?'重溫教學':'新手教學';
      $('#continueBtn').classList.toggle('hidden',!hasPersistentSave())
    }
    function selectedEntities(){return game?[...game.selected].map(entityById).filter(Boolean):[]}
    function setSelected(list,add=false){if(!game)return;if(!add)game.selected.clear();for(const e of list)if(e&&!e.dead&&e.faction===0)game.selected.add(e.id);for(const e of game.entities)e.selected=game.selected.has(e.id);tutorialEvent('selected');Audio.sfx('select');updateHUD(true)}
    let selectionCycle={x:-9999,y:-9999,signature:'',index:0,time:-1e9};
    function resetSelectionCycle(){selectionCycle={x:-9999,y:-9999,signature:'',index:0,time:-1e9}}
    function unitScreenHitRadius(u){const d=UNIT[u.type],role=d?.role,base=role==='siege'?24:role==='cavalry'?22:19;return Math.max(20,(u.radius+base)*game.camera.zoom)}
    function friendlyUnitHitsAtScreen(sx,sy){if(!game)return[];const hits=[];for(const u of game.entities){if(u.dead||u.faction!==0||u.kind!=='unit'||!visibleAt(u.x,u.y))continue;const p=worldToScreen(u.x,u.y),r=unitScreenHitRadius(u),dx=sx-p.x,dy=sy-p.y,score=(dx*dx+dy*dy)/(r*r);if(score<=1)hits.push({u,score,distance:dx*dx+dy*dy})}return hits.sort((a,b)=>a.score-b.score||a.distance-b.distance||a.u.id-b.u.id).map(hit=>hit.u)}
    function friendlyBuildingHitsAtScreen(sx,sy){if(!game)return[];const hits=[];for(const b of game.entities){if(b.dead||b.faction!==0||b.kind!=='building'||!visibleAt(b.x,b.y))continue;const p=worldToScreen(b.x,b.y),r=Math.max(18,b.radius*game.camera.zoom),dx=sx-p.x,dy=sy-p.y,score=(dx*dx+dy*dy)/(r*r);if(score<=1)hits.push({b,score,distance:dx*dx+dy*dy})}return hits.sort((a,b)=>a.score-b.score||a.distance-b.distance||a.b.id-b.b.id).map(hit=>hit.b)}
    function selectAt(sx,sy,add=false,double=false,time=performance.now()){
      const units=friendlyUnitHitsAtScreen(sx,sy),hits=units.length?units:friendlyBuildingHitsAtScreen(sx,sy);if(!hits.length){resetSelectionCycle();setSelected([],add);return}const signature=`${units.length?'u':'b'}:${hits.map(e=>e.id).join(',')}`,repeat=hits.length>1&&signature===selectionCycle.signature&&Math.hypot(sx-selectionCycle.x,sy-selectionCycle.y)<=12&&time-selectionCycle.time<=1300,index=repeat?(selectionCycle.index+1)%hits.length:0,best=hits[index];selectionCycle={x:sx,y:sy,signature,index,time};
      if(double&&hits.length===1&&best.kind==='unit'){const found=game.entities.filter(e=>!e.dead&&e.faction===0&&e.kind==='unit'&&e.type===best.type&&worldToScreen(e.x,e.y).x>=0&&worldToScreen(e.x,e.y).x<=viewW&&worldToScreen(e.x,e.y).y>=0&&worldToScreen(e.x,e.y).y<=viewH);setSelected(found,add)}else{setSelected([best],add);if(hits.length>1)toast(`重疊 ${hits.length} 個${units.length?'單位':'建築'} · 已選第 ${index+1} 個，再點可切換`)}
    }
    function selectRect(x1,y1,x2,y2,add=false){resetSelectionCycle();const l=Math.min(x1,x2),r=Math.max(x1,x2),t=Math.min(y1,y2),b=Math.max(y1,y2),inside=e=>{const p=worldToScreen(e.x,e.y);return p.x>=l&&p.x<=r&&p.y>=t&&p.y<=b};let found=game.entities.filter(e=>!e.dead&&e.faction===0&&e.kind==='unit'&&inside(e));if(!found.length)found=game.entities.filter(e=>!e.dead&&e.faction===0&&e.kind==='building'&&inside(e));setSelected(found,add)}
    function targetAtScreen(sx,sy,includeResources=true){const hits=[];for(const e of game.entities){if(e.dead||!visibleAt(e.x,e.y))continue;const own=e.faction===0,actionable=!own||(e.kind==='building'&&(e.type==='farm'||e.construction<1));if(!actionable)continue;const p=worldToScreen(e.x,e.y),r=e.kind==='unit'?Math.max(20,(e.radius+18)*game.camera.zoom):Math.max(18,e.radius*game.camera.zoom),dx=sx-p.x,dy=sy-p.y,d2=dx*dx+dy*dy;if(d2<=r*r)hits.push({e,score:d2/(r*r),priority:!own&&e.kind==='unit'?0:!own?1:2})}if(includeResources)for(const n of game.nodes){if(n.dead||!visibleAt(n.x,n.y))continue;const p=worldToScreen(n.x,n.y),r=Math.max(17,(n.radius+7)*game.camera.zoom),dx=sx-p.x,dy=sy-p.y,d2=dx*dx+dy*dy;if(d2<=r*r)hits.push({e:n,score:d2/(r*r),priority:2})}return hits.sort((a,b)=>a.priority-b.priority||a.score-b.score||a.e.id-b.e.id)[0]?.e||null}
    function issueContext(x,y,sx=null,sy=null){
      const sel=selectedEntities().filter(e=>e.kind==='unit');if(!sel.length)return;tutorialEvent('order');const t=sx===null?null:targetAtScreen(sx,sy,true);
      if(t&&t.faction!==undefined&&t.faction!==0){for(const u of sel)setAttack(u,t);marker(t.x,t.y,'attack');Audio.sfx('move');return}
      if(t&&(t.kind==='resource'||(t.kind==='building'&&t.type==='farm'&&t.faction===0))){for(const u of sel)if(u.type==='villager')setGather(u,t);marker(t.x,t.y,'gather');Audio.sfx('move');return}
      if(t&&t.kind==='building'&&t.faction===0&&t.construction<1){for(const u of sel)if(u.type==='villager')setBuild(u,t);marker(t.x,t.y,'gather');Audio.sfx('build');return}
      const movable=sel,cols=Math.ceil(Math.sqrt(movable.length)),spacing=30;movable.forEach((u,i)=>{const row=Math.floor(i/cols),col=i%cols,ox=(col-(Math.min(cols,movable.length)-1)/2)*spacing,oy=(row-(Math.ceil(movable.length/cols)-1)/2)*spacing;setMove(u,x+ox,y+oy,'move')});marker(x,y,'move');Audio.sfx('move')
    }
    function issueAttackMove(x,y){const sel=selectedEntities().filter(e=>e.kind==='unit'&&UNIT[e.type].role!=='worker');if(!sel.length){toast('請先選取軍事單位。');return}const cols=Math.ceil(Math.sqrt(sel.length));sel.forEach((u,i)=>setMove(u,x+(i%cols-(cols-1)/2)*28,y+(Math.floor(i/cols)-1)*28,'attackMove'));marker(x,y,'attack');tutorialEvent('attackMove');Audio.sfx('move')}
    function validBuildAt(type,x,y){const d=BUILD[type];if(!d||x<d.size+8||y<d.size+8||x>WORLD_W-d.size-8||y>WORLD_H-d.size-8||!isLandPx(x,y))return false;for(const e of game.entities)if(!e.dead&&dist(e,{x,y})<e.radius+d.size+9)return false;for(const n of game.nodes)if(!n.dead&&dist(n,{x,y})<n.radius+d.size+5)return false;if((type==='tower'||type==='wall')&&game.sites.some(s=>dist(s,{x,y})<150))return false;return true}
    const BUILD_PREREQUISITES={farm:['mill'],range:['barracks'],stable:['barracks'],workshop:['blacksmith'],castle:['blacksmith']},BUILD_NAMES={mill:'磨坊',lumber:'伐木場',barracks:'軍營',blacksmith:'鐵匠鋪'};
    function missingBuildPrerequisite(type,faction=0){return(BUILD_PREREQUISITES[type]||[]).find(req=>!ownsCompletedBuilding(faction,req))||null}
    function startBuild(type){const d=BUILD[type],p=game.player;if(!d||p.age<d.age){toast(`需進入${AGES[d?.age-1]||'更高時代'}。`);return}const missing=missingBuildPrerequisite(type);if(missing){toast(`需先完成${BUILD_NAMES[missing]||BUILD[missing]?.name}。`);return}if(type==='tower'&&game.entities.filter(e=>!e.dead&&e.faction===0&&e.type==='tower').length>=4){toast('箭塔上限為四座。');return}if(type==='wonder'&&game.entities.some(e=>!e.dead&&e.faction===0&&e.type==='wonder')){toast('世界奇觀只能興建一座。');return}if(!canAfford(p,civAdjustedCost({...d,key:type},p.civ))){toast('資源不足。');return}buildMode=type;attackMove=false;dom.buildHint.classList.remove('hidden');Audio.sfx('click')}
    function placeBuild(x,y){if(!buildMode)return;const type=buildMode,d=BUILD[type],cost=civAdjustedCost({...d,key:type},game.player.civ);if(!validBuildAt(type,x,y)){toast('此處無法興建。');Audio.sfx('alert');return}if(!spend(game.player,cost)){toast('資源不足。');cancelMode();return}const b=createBuilding(type,0,x,y,0);const workers=selectedEntities().filter(e=>e.kind==='unit'&&e.type==='villager').slice(0,5);for(const u of workers)setBuild(u,b);marker(x,y,'gather');tutorialEvent('buildPlaced',type);game.stats.built++;Audio.sfx('build');if(!keys.has('Shift'))cancelMode();updateHUD(true)}
    function cancelMode(){buildMode=null;attackMove=false;dom.buildHint.classList.add('hidden')}
    function research(kind){const p=game.player,levels={attack:3,armor:3,economy:2};if(p.age<2){toast('科技於封建時代解鎖。');return}if(p.tech[kind]>=levels[kind]){toast('此項科技已臻至頂峰。');return}const lv=p.tech[kind]+1,cost=kind==='economy'?{food:120*lv,wood:100*lv}:kind==='attack'?{food:150*lv,gold:100*lv}:{food:110*lv,gold:110*lv};if(!spend(p,cost)){toast('研究所需資源不足。');return}p.tech[kind]++;const label={attack:'精鍛武器',armor:'鱗片護甲',economy:'行會制度'}[kind];if(kind==='armor')for(const u of game.entities)if(!u.dead&&u.faction===0&&u.kind==='unit')u.armor++;notify(`${label}研究完成（第 ${lv} 級）。`,'good');tutorialEvent('tech');Audio.sfx('age');updateHUD(true)}
    function buttonHtml(action,glyph,label,cost='',disabled=false,hotkey='',tip=''){const atlasClass={"build:house":'atlas-command atlas-house',"build:castle":'atlas-command atlas-castle',age:'atlas-command atlas-age'}[action]||'';return`<button type="button" class="cmd${atlasClass?` ${atlasClass}`:''}" data-action="${action}" data-tip="${escapeHtml(tip||label)}" ${disabled?'disabled':''}><span class="hotkey">${hotkey}</span><span class="glyph">${glyph}</span>${label}${cost?`<span class="cost">${cost}</span>`:''}</button>`}
    function commandSet(sel){
      if(!sel.length)return'';const one=sel.length===1?sel[0]:null;let out='';
      if(one?.kind==='building'){
        const b=one,p=game.player;let train=[...(TRAIN_AT[b.type]||[])];const uq=CIVS[p.civ].unique,ud=UNIT[uq];if(ud&&(ud.trainAt===b.type||(!ud.trainAt&&((b.type==='range'&&ud.role==='ranged')||(b.type==='stable'&&ud.role==='cavalry')||(b.type==='barracks'&&ud.role==='infantry')))))train.push(uq);
        for(const t of train){const d=UNIT[t],locked=p.age<d.age;out+=buttonHtml(`train:${t}`,d.glyph,d.name,costText(civAdjustedCost(d,p.civ)),locked,'',locked?`需要${AGES[d.age-1]}`:d.desc)}
        if(b.type==='town'&&p.age<4){const c=ageCost(p),req=ageRequirement(p);out+=buttonHtml('age','代',p.ageUp?'晉升中':`晉升${AGES[p.age]}`,costText(c),!!p.ageUp,'',req.met?'解鎖新建築、兵種與科技。':req.text)}
        if(b.type==='blacksmith'){out+=buttonHtml('tech:economy','穀','經濟科技',`第 ${p.tech.economy+1} 級`,p.tech.economy>=2,'','提高所有採集效率。');out+=buttonHtml('tech:attack','刃','武器科技',`第 ${p.tech.attack+1} 級`,p.tech.attack>=3,'','提高全軍攻擊力。');out+=buttonHtml('tech:armor','甲','護甲科技',`第 ${p.tech.armor+1} 級`,p.tech.armor>=3,'','提高全軍護甲。')}
        out+=buttonHtml('rally','旗','設定集結點','',false,'','下一次點擊地面以設定新兵集結點。');
      }else{
        out+=buttonHtml('attackmove','攻','攻擊移動','',false,'A','沿途主動迎戰敵軍。');out+=buttonHtml('stop','止','停止','',false,'S','取消目前所有命令。');
        if(sel.some(e=>e.type==='villager'))for(const t of BUILD_ORDER){const d=BUILD[t],locked=game.player.age<d.age;out+=buttonHtml(`build:${t}`,d.glyph,d.name,costText(civAdjustedCost({...d,key:t},game.player.civ)),locked,'',locked?`需要${AGES[d.age-1]}`:d.desc)}
      }return out
    }
    function selectionPanelHtml(sel){
      if(!sel.length)return'<div class="empty-selection">尚未選取單位<br>左鍵點選，或拖曳框選軍隊</div>';
      if(sel.length>1){const units=sel.filter(e=>e.kind==='unit'),hp=units.reduce((s,e)=>s+e.hp,0),max=units.reduce((s,e)=>s+e.maxHp,0),working=units.filter(e=>{const a=unitActivityState(e);return a.active&&(a.kind==='gather'||a.kind==='build')}).length,types={};for(const e of units)types[e.type]=(types[e.type]||0)+1;return`<div class="selection-head"><div class="portrait">軍</div><div class="selection-title"><h3>${units.length} 支部隊</h3><p>${working?`${working} 人工作中 · `:''}混合編隊 · 右鍵下令</p></div></div><div class="healthbar"><i style="width:${max?hp/max*100:0}%"></i></div><div class="selection-grid">${Object.entries(types).map(([t,n])=>`<span class="unit-dot" title="${UNIT[t].name} × ${n}">${UNIT[t].glyph}</span>`).join('')}</div>`}
      const e=sel[0],d=e.kind==='unit'?UNIT[e.type]:BUILD[e.type],activity=e.kind==='unit'?unitActivityState(e):null,activityText=activity&&activity.kind!=='idle'?` · ${activity.label}`:'',sub=e.kind==='unit'?`${d.role==='worker'?'百姓':d.role==='infantry'?'步兵':d.role==='ranged'?'遠程':d.role==='cavalry'?'騎兵':'攻城器'} · ${CIVS[e.civ].name}${activityText}`:`${e.construction<1?`施工 ${Math.floor(e.construction*100)}%`:'建築'} · ${CIVS[e.civ].name}`,stats=e.kind==='unit'?`攻擊 ${Math.round(e.damage+game.player.tech.attack)}　護甲 ${e.armor}　速度 ${Math.round(e.speed)}`:`生命 ${Math.ceil(e.hp)}／${e.maxHp}`;return`<div class="selection-head"><div class="portrait" style="color:${teamColor(e)}">${d.glyph}</div><div class="selection-title"><h3>${d.name}</h3><p>${sub}</p></div></div><div class="healthbar"><i style="width:${clamp(e.hp/e.maxHp*100,0,100)}%"></i></div><div class="stats">${stats}</div><div class="help-line">${d.desc}</div>`
    }
    function queuePanelHtml(sel){const b=sel.length===1&&sel[0].kind==='building'?sel[0]:null;if(!b)return'<h4>戰術提示</h4><div class="help-line">長槍兵克騎兵；騎兵克遠程；弓兵克長槍；攻城器克建築。按 F 可發動文明軍令。</div>';let html='<h4>生產與研發</h4>';if(game.player.ageUp)html+=`<div class="queue-row">晉升${AGES[game.player.age]}<div class="queue-progress"><i style="width:${(1-game.player.ageUp.remaining/game.player.ageUp.total)*100}%"></i></div></div>`;if(!b.queue.length&&!game.player.ageUp)html+='<div class="help-line">目前沒有生產項目。</div>';for(const q of b.queue)html+=`<div class="queue-row">${UNIT[q.type].name} · ${Math.ceil(q.remaining)} 秒<div class="queue-progress"><i style="width:${(1-q.remaining/q.total)*100}%"></i></div></div>`;return html}
    function updateHUD(force=false){
      if(!game)return;const p=game.player;dom.resources.innerHTML=Object.entries(RES).map(([k,r])=>`<div class="res-chip atlas-resource atlas-${k}"><span class="res-icon">${r.glyph}</span><span><span class="res-label">${r.name}</span><b class="res-val">${fmt(p.res[k])}</b></span></div>`).join('')+`<div class="res-chip"><span class="res-icon">人</span><span><span class="res-label">人口</span><b class="res-val">${p.pop}／${Math.min(MAX_POP,p.popCap)}</b></span></div>`;
      dom.age.textContent=p.ageUp?`${AGES[p.age-1]} · 晉升 ${Math.ceil(p.ageUp.remaining)} 秒`:AGES[p.age-1];dom.clock.textContent=formatTime(game.time);dom.civ.textContent=`${CIVS[p.civ].name} · ${game.players.filter(q=>!q.eliminated).length} 方存續`;
      const ready=Math.max(0,(p.powerReady||0)-game.time),ability=$('#abilityBtn');ability.classList.add('atlas-ability');ability.textContent=ready?`${Math.ceil(ready)}秒`:CIVS[p.civ].power;ability.title=`${CIVS[p.civ].power}：${CIVS[p.civ].powerDesc}`;$('#speedBtn').textContent=`${game.speed}×`;$('#muteBtn').textContent=Audio.muted?'靜音':'聲音';
      const own=game.sites.filter(s=>s.owner===0).length,remaining=game.players.slice(1).filter(q=>!q.eliminated).length,total=game.players.length-1;$('#supremacyText').innerHTML=`<span>王旗據點</span><b>${own}／3</b>`;$('#supremacyBar').style.width=`${clamp(game.supremacy[0]/90*100,0,100)}%`;$('#objectiveText').innerHTML=`<span>征服敵方城鎮</span><b>${total-remaining}／${total}</b>`;
      const sel=selectedEntities();dom.selection.innerHTML=selectionPanelHtml(sel);dom.commands.innerHTML=commandSet(sel);dom.queue.innerHTML=queuePanelHtml(sel);bindTooltips();if(force)renderTutorial()
    }
    function bindTooltips(){$$('.cmd[data-tip]').forEach(b=>{b.addEventListener('mouseenter',()=>showTip(b,b.dataset.tip));b.addEventListener('mouseleave',hideTip)})}
    function showTip(el,text){const r=el.getBoundingClientRect();dom.tooltip.innerHTML=`<div class="tip-title">${escapeHtml(el.textContent.replace(/\s+/g,' ').trim())}</div>${escapeHtml(text)}`;dom.tooltip.classList.remove('hidden');const tr=dom.tooltip.getBoundingClientRect();dom.tooltip.style.left=clamp(r.left,8,viewW-tr.width-8)+'px';dom.tooltip.style.top=Math.max(8,r.top-tr.height-8)+'px'}
    function hideTip(){dom.tooltip.classList.add('hidden')}

    let lastSelectTime=0,rallyMode=null,touchCommandMode=false;
    const canvasPoint=e=>{const r=dom.canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
    const canvasContainsPoint=p=>p.x>=0&&p.y>=0&&p.x<=viewW&&p.y<=viewH;
    function handleCommand(action){
      if(!game||game.paused)return;Audio.sfx('click');if(action.startsWith('train:')){const b=selectedEntities()[0];if(b)queueUnit(b,action.split(':')[1])}
      else if(action.startsWith('build:'))startBuild(action.split(':')[1]);else if(action.startsWith('tech:'))research(action.split(':')[1]);else if(action==='age')beginAgeUp(game.player);
      else if(action==='attackmove'){cancelMode();attackMove=true;dom.buildHint.textContent='選擇攻擊移動位置 · 左鍵確認 · 右鍵取消';dom.buildHint.classList.remove('hidden')}
      else if(action==='stop'){for(const u of selectedEntities())if(u.kind==='unit')stopUnit(u);cancelMode();updateHUD(true)}
      else if(action==='rally'){const b=selectedEntities()[0];if(b?.kind==='building'){rallyMode=b.id;dom.buildHint.textContent='選擇新兵集結位置 · 左鍵確認 · 右鍵取消';dom.buildHint.classList.remove('hidden')}}
    }
    dom.commands.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled)handleCommand(b.dataset.action)});
    dom.canvas.addEventListener('pointerenter',e=>{const q=canvasPoint(e);mouse.inside=true;mouse.x=q.x;mouse.y=q.y;if(game){const p=screenToWorld(q.x,q.y);mouse.worldX=p.x;mouse.worldY=p.y}});
    dom.canvas.addEventListener('pointerleave',()=>{if(!mouse.down)mouse.inside=false});
    dom.canvas.addEventListener('pointerdown',e=>{
      if(!game||game.paused||e.button===1)return;if(e.button===2)e.preventDefault();Audio.init();const q=canvasPoint(e),p=screenToWorld(q.x,q.y);mouse.x=q.x;mouse.y=q.y;mouse.worldX=p.x;mouse.worldY=p.y;mouse.down=true;mouse.startX=mouse.x;mouse.startY=mouse.y;mouse.button=e.button;mouse.drag=false;mouse.pan=e.button===2;mouse.inside=true;dom.canvas.setPointerCapture?.(e.pointerId);if(mouse.pan)dom.canvas.style.cursor='grabbing'
    });
    dom.canvas.addEventListener('pointermove',e=>{
      const q=canvasPoint(e),nx=q.x,ny=q.y;mouse.inside=canvasContainsPoint(q);if(mouse.down){const dx=nx-mouse.x,dy=ny-mouse.y;if(Math.hypot(nx-mouse.startX,ny-mouse.startY)>5)mouse.drag=true;if(mouse.pan&&game&&(dx||dy)){resetSelectionCycle();panCameraScreen(-dx,-dy);tutorialEvent('camera')}}mouse.x=nx;mouse.y=ny;if(game){const p=screenToWorld(nx,ny);mouse.worldX=p.x;mouse.worldY=p.y}
    });
    dom.canvas.addEventListener('pointerup',e=>{
      if(!game||game.paused)return;const wasPan=mouse.pan,didDrag=mouse.drag,p=screenToWorld(mouse.x,mouse.y);mouse.down=false;mouse.pan=false;mouse.inside=canvasContainsPoint(canvasPoint(e));dom.canvas.style.cursor='default';if(e.button===2){e.preventDefault();if(didDrag)return;if(buildMode||attackMove||rallyMode){cancelMode();rallyMode=null;return}issueContext(p.x,p.y,mouse.x,mouse.y);return}if(wasPan||e.button!==0)return;
      if(buildMode){placeBuild(p.x,p.y);return}if(rallyMode){const b=entityById(rallyMode);if(b){b.rally={x:p.x,y:p.y};marker(p.x,p.y,'move');tutorialEvent('rally');toast('新兵集結點已設定。')}rallyMode=null;dom.buildHint.classList.add('hidden');return}
      if(attackMove){issueAttackMove(p.x,p.y);cancelMode();return}if(touchCommandMode){issueContext(p.x,p.y,mouse.x,mouse.y);touchCommandMode=false;$('#touchCommand').style.background='';return}
      if(mouse.drag&&(e.pointerType!=='touch'||touchSelectMode))selectRect(mouse.startX,mouse.startY,mouse.x,mouse.y,e.shiftKey);else{const dbl=e.timeStamp-lastSelectTime<330;selectAt(mouse.x,mouse.y,e.shiftKey,dbl,e.timeStamp);lastSelectTime=e.timeStamp}touchSelectMode=false;$('#touchSelect').style.background=''
    });
    dom.canvas.addEventListener('contextmenu',e=>e.preventDefault());
    dom.canvas.addEventListener('wheel',e=>{if(!game||game.paused)return;e.preventDefault();resetSelectionCycle();const q=canvasPoint(e);zoomCameraAt(q.x,q.y,clamp(game.camera.zoom*Math.exp(-e.deltaY*.001),.62,1.65));tutorialEvent('camera')},{passive:false});
    dom.minimap.addEventListener('pointerdown',e=>{if(!game||game.paused)return;resetSelectionCycle();const r=dom.minimap.getBoundingClientRect(),scale=Math.min((r.width-8)/WORLD_W,(r.height-8)/WORLD_H),ox=(r.width-WORLD_W*scale)/2,oy=(r.height-WORLD_H*scale)/2,x=clamp((e.clientX-r.left-ox)/scale,0,WORLD_W),y=clamp((e.clientY-r.top-oy)/scale,0,WORLD_H);centerCamera(x,y);tutorialEvent('camera');Audio.sfx('click')});
    function updateCamera(dt){if(!game||game.paused)return;let dx=0,dy=0;if(keys.has('w')||keys.has('ArrowUp'))dy--;if(keys.has('s')||keys.has('ArrowDown'))dy++;if(keys.has('a')||keys.has('ArrowLeft'))dx--;if(keys.has('d')||keys.has('ArrowRight'))dx++;if(mouse.inside&&mouse.y<viewH-175&&!mouse.down){if(mouse.x<5)dx--;if(mouse.x>viewW-5)dx++;if(mouse.y<5)dy--;if(mouse.y>viewH-5)dy++}if(dx||dy){resetSelectionCycle();const n=Math.hypot(dx,dy),speed=530;panCameraScreen(dx/n*speed*dt,dy/n*speed*dt);tutorialEvent('camera')}}
    addEventListener('keydown',e=>{
      if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();keys.add(e.key.length===1?e.key.toLowerCase():e.key);if(!game||dom.game.classList.contains('hidden'))return;
      if(e.key==='Escape'){if(!$('#guideOverlay').classList.contains('hidden'))closeGuide();else if(buildMode||attackMove||rallyMode){cancelMode();rallyMode=null}else togglePause(!game.paused);return}
      if(e.code==='Space'){togglePause(!game.paused);return}if(game.paused)return;
      const k=e.key.toLowerCase();if(k==='a'){cancelMode();attackMove=true;dom.buildHint.textContent='選擇攻擊移動位置 · 左鍵確認 · 右鍵取消';dom.buildHint.classList.remove('hidden')}if(k==='s'){for(const u of selectedEntities())if(u.kind==='unit')stopUnit(u);cancelMode()}if(k==='f')usePower(0);if(k==='h'){const tc=game.entities.find(x=>!x.dead&&x.faction===0&&x.type==='town');if(tc)centerCamera(tc.x,tc.y)}
      const groupKey=/^Digit([1-4])$/.exec(e.code);if(groupKey&&!e.ctrlKey&&!e.altKey&&!e.metaKey){e.preventDefault();const n=Number(groupKey[1]);if(e.shiftKey){controlGroups[n-1]=[...game.selected];tutorialEvent('group');toast(`第 ${n} 編隊已建立。`)}else{const list=controlGroups[n-1].map(entityById).filter(Boolean);if(list.length){setSelected(list);const cx=list.reduce((s,u)=>s+u.x,0)/list.length,cy=list.reduce((s,u)=>s+u.y,0)/list.length;centerCamera(cx,cy)}}}
    });
    addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));
    addEventListener('blur',()=>{keys.clear();mouse.inside=false;mouse.down=false;mouse.pan=false;dom.canvas.style.cursor='default'});addEventListener('resize',resize);
    $('#touchSelect').addEventListener('click',()=>{touchSelectMode=!touchSelectMode;$('#touchSelect').style.background=touchSelectMode?'#846332':''});
    $('#touchCommand').addEventListener('click',()=>{touchCommandMode=!touchCommandMode;$('#touchCommand').style.background=touchCommandMode?'#846332':''});

    const TUTORIAL_STEPS=[
      {title:'環顧俯視戰場',body:'按住滑鼠右鍵拖曳即可平移 2D 地圖；WASD、畫面邊緣與小地圖也能移動視角，滾輪則縮放。滑鼠中鍵完全不使用。',hint:'目標：平移或縮放一次戰場',check:()=>game.tutorial.flags.camera},
      {title:'選取你的人民',body:'左鍵點選村民；每個單位都有寬鬆且不受建築遮擋的選取範圍。拖曳左鍵可框選，Shift 可追加，連按兩下會選取畫面內同兵種；重疊時連點同處可逐一切換。',hint:'目標：選取至少一名村民',check:()=>selectedEntities().some(e=>e.type==='villager')},
      {title:'快速右鍵下令',body:'在空地快速按一下右鍵可移動。右鍵拖曳只會平移，不會誤下命令；對資源、敵軍或工地快速右鍵會自動採集、攻擊或施工。',hint:'目標：向選取單位下達一次移動命令',check:()=>game.tutorial.flags.order},
      {title:'維持帝國經濟',body:'把村民分派至食物、木材、黃金與石材。食物支撐人口，木材建造，黃金與石材則供應精銳軍隊、防禦與奇觀。',hint:'目標：累積採集至少 12 單位資源',check:()=>game.stats.gathered>=(game.tutorial.gatherStart||0)+12,grant:{food:380,wood:360,gold:220,stone:180}},
      {title:'安家、磨坊與屯田',body:'先興建磨坊，便能在其周圍開闢農田；房舍提高人口上限。選好建築後用左鍵放置、右鍵取消，這就是《帝王世紀》式的建築前置關係。',hint:'目標：完成磨坊、房舍與農田',check:()=>['mill','house','farm'].every(t=>game.entities.some(e=>!e.dead&&e.faction===0&&e.type===t&&e.construction>=1)),grant:{wood:520}},
      {title:'人口、生產與集合點',body:'選取城鎮中心訓練一名村民，再按「設定集結點」並以左鍵指定位置。人口滿時須先蓋房舍；生產佇列與進度顯示在下方。',hint:'目標：擁有至少 6 名村民，並設定集合點',check:()=>game.entities.filter(e=>!e.dead&&e.faction===0&&e.type==='villager').length>=6&&game.tutorial.flags.rally,grant:{food:260}},
      {title:'保存與可攜存檔',body:'空白鍵可暫停。暫停選單能儲存至瀏覽器，遊戲也每 30 秒自動保存；「匯出存檔」會下載 JSON，可在另一個瀏覽器匯入。',hint:'目標：儲存一次，並匯出一次 JSON 存檔',check:()=>game.tutorial.flags.saved&&game.tutorial.flags.exported},
      {title:'晉升時代與鐵匠鋪',body:'磨坊與伐木場完工後，可在城鎮中心晉升封建時代；再興建鐵匠鋪研究經濟或軍事科技。封建、城堡與帝王時代會逐步解鎖完整科技樹。',hint:'目標：到達封建時代並研究一項科技',check:()=>game.player.age>=2&&Object.values(game.player.tech).some(v=>v>0),grant:{food:820,gold:430,wood:620}},
      {title:'組建剋制軍隊',body:'軍營是靶場與馬廄的前置建築。長槍克騎兵、騎兵克遠程、弓兵壓制長槍、攻城器克建築；城堡時代可建造城堡並訓練文明獨特兵種。',hint:'目標：完成軍營並擁有至少兩名軍事單位',check:()=>game.entities.some(e=>!e.dead&&e.faction===0&&e.type==='barracks'&&e.construction>=1)&&game.entities.filter(e=>!e.dead&&e.faction===0&&e.kind==='unit'&&UNIT[e.type].role!=='worker').length>=2,grant:{food:520,wood:420,gold:260}},
      {title:'編隊與攻擊移動',body:'Shift＋1～4 儲存編隊，數字鍵選取並聚焦；這組操作不會觸發 Chrome 分頁切換。按 A 或指令列的「攻擊移動」，再點地面，軍隊會在行進中主動迎敵；S 立即停止。',hint:'目標：建立一組編隊並下達攻擊移動',check:()=>game.tutorial.flags.group&&game.tutorial.flags.attackMove},
      {title:'發動文明軍令',body:'每個文明都有彼此平衡的專屬軍令。封建時代後按 F 或頂列軍令按鈕發動；時機往往比單純兵力更重要。',hint:'目標：發動一次文明軍令',check:()=>game.tutorial.flags.power},
      {title:'爭奪王旗霸權',body:'讓非村民軍隊站在王旗附近六秒即可佔領。據點提供黃金；同時控制三座並維持 90 秒，便能取得霸權勝利。',hint:'目標：奪下一座王旗',check:()=>game.sites.some(s=>s.owner===0),grant:{food:300,gold:220}},
      {title:'決定天下',body:'你已掌握核心機制。征服所有敵方城鎮中心、連續控制三座王旗，或在帝王時代興建並守住世界奇觀都能勝利。多人混戰中，各 AI 會依難度擴張、反制與互相交戰。',hint:'教學完成；按下方按鈕釋放敵軍，繼續這場戰局。',check:()=>false}
    ];
    function tutorialEvent(type,payload=true){if(!game?.tutorial?.active||game.tutorial.completed)return;const f=game.tutorial.flags||(game.tutorial.flags={});if(typeof payload==='number')f[type]=(f[type]||0)+payload;else f[type]=payload||true}
    function enterTutorialStep(step){const t=game.tutorial;if(!t||t.granted?.includes(step))return;t.granted=t.granted||[];t.granted.push(step);const def=TUTORIAL_STEPS[step];if(def?.grant)for(const[k,v]of Object.entries(def.grant))game.player.res[k]=Math.max(game.player.res[k],v);if(step===3)t.gatherStart=game.stats.gathered;if(step===10)game.player.powerReady=0;if(step===11&&game.sites[0]){centerCamera(game.sites[0].x,game.sites[0].y);marker(game.sites[0].x,game.sites[0].y,'gather')}notify(`教學：${def.title}`,'good');updateHUD(true)}
    function renderTutorial(){if(!game?.tutorial?.active||game.tutorial.completed){$('#tutorialPanel').classList.add('hidden');return}const step=clamp(game.tutorial.step||0,0,TUTORIAL_STEPS.length-1),def=TUTORIAL_STEPS[step];$('#tutorialPanel').classList.remove('hidden');$('#tutorialStep').textContent=`教學 ${step+1}／${TUTORIAL_STEPS.length}`;$('#tutorialProgress').style.width=`${(step+1)/TUTORIAL_STEPS.length*100}%`;$('#tutorialTitle').textContent=def.title;$('#tutorialBody').textContent=def.body;$('#tutorialHint').textContent=def.hint;$('#tutorialSkipBtn').textContent=step===TUTORIAL_STEPS.length-1?'完成教學':'略過此步'}
    function updateTutorial(dt=0){const t=game?.tutorial;if(!t?.active||t.completed)return;t.checkIn=(t.checkIn||0)-dt;if(t.checkIn>0)return;t.checkIn=.25;const step=t.step||0,def=TUTORIAL_STEPS[step];if(step<TUTORIAL_STEPS.length-1&&def?.check()){t.step=step+1;enterTutorialStep(t.step);renderTutorial();persistGame(true)}}
    function finishTutorial(markComplete=true){if(!game?.tutorial)return;game.tutorial.active=false;game.tutorial.completed=markComplete;$('#tutorialPanel').classList.add('hidden');if(markComplete){try{localStorage.setItem(TUTORIAL_DONE_KEY,'1')}catch{}notify('教學完成！敵軍開始全面行動，願你的帝國長存。','good');Audio.sfx('win')}else notify('已結束引導；你仍可從玩法指南查閱所有操作。');persistGame(true);renderMenuState()}
    $('#tutorialSkipBtn').addEventListener('click',()=>{if(!game?.tutorial?.active)return;if((game.tutorial.step||0)>=TUTORIAL_STEPS.length-1)finishTutorial(true);else{game.tutorial.step++;enterTutorialStep(game.tutorial.step);renderTutorial()}});$('#tutorialEndBtn').addEventListener('click',()=>finishTutorial(false));

    function togglePause(on){if(!game||game.ended)return;game.paused=on;$('#pauseOverlay').classList.toggle('hidden',!on);$('#pauseSummary').textContent=`${CIVS[game.player.civ].name} · ${AGES[game.player.age-1]} · 戰局 ${formatTime(game.time)}`;if(!on){last=performance.now();accumulator=0;Audio.ctx?.resume()}updateHUD(true)}
    function openGuide(){game&&(game.wasPausedForGuide=game.paused,game.paused=true);$('#guideOverlay').classList.remove('hidden')}
    function closeGuide(){$('#guideOverlay').classList.add('hidden');if(game&&!game.wasPausedForGuide&&!dom.game.classList.contains('hidden'))game.paused=false}
    function returnMenu(){if(game&&!game.ended)persistGame(true);if(game)game.running=false;game=null;cancelMode();rallyMode=null;$('#pauseOverlay').classList.add('hidden');$('#endOverlay').classList.add('hidden');$('#guideOverlay').classList.add('hidden');dom.game.classList.add('hidden');dom.menu.classList.remove('hidden');dom.notices.innerHTML='';Audio.stop();renderMenuState()}
    function currentCivKey(key){const migrated=LEGACY_CIV_MAP[key]||key;return CIVS[migrated]?migrated:(CIVS.britons?'britons':Object.keys(CIVS)[0])}
    function rebuildSnapshotDerived(g,players){for(const p of players){p.pop=0;p.popCap=0}for(const e of g.entities||[]){const p=players[e.faction],civ=p?.civ||currentCivKey(e.civ),mods=civMods(civ),oldMax=Math.max(1,Number(e.maxHp)||Number(e.hp)||1),ratio=clamp((Number(e.hp)||oldMax)/oldMax,0,1);e.civ=civ;if(e.kind==='unit'){const d=UNIT[e.type];if(!d)continue;e.radius=d.role==='siege'?16:d.role==='cavalry'?13:10;e.maxHp=Math.round(d.hp*roleModifier(mods.unitHp,d,e.type,1));e.hp=Math.max(1,e.maxHp*ratio);e.armor=d.armor+roleModifier(mods.unitArmor,d,e.type,0)+(p?.tech?.armor||0);e.speed=d.speed*roleModifier(mods.unitSpeed,d,e.type,1);e.damage=d.damage*roleModifier(mods.unitDamage,d,e.type,1);e.range=d.range*roleModifier(mods.unitRange,d,e.type,1);e.cool=d.cool*roleModifier(mods.unitCooldown,d,e.type,1);if(p)p.pop+=d.pop}else if(e.kind==='building'){const d=BUILD[e.type];if(!d)continue;e.radius=d.size;e.maxHp=Math.round(d.hp*(mods.buildingHp||1));e.hp=Math.max(1,e.maxHp*ratio);if(p&&e.construction>=1&&d.pop)p.popCap+=d.pop;if(Array.isArray(e.queue))for(const q of e.queue){if(LEGACY_UNIT_MAP[q.type]&&UNIT[LEGACY_UNIT_MAP[q.type]])q.type=LEGACY_UNIT_MAP[q.type]}}}for(const p of players){p.pop=Math.max(0,Math.round(p.pop));p.popCap=clamp(Math.round(p.popCap),0,MAX_POP)}}
    function migrateSnapshot(s){if(!s?.game)return s;const g=s.game,players=Array.isArray(g.players)?g.players:[g.player,g.enemy].filter(Boolean);let migrated=false;const chosen=currentCivKey(s.chosenCiv||players[0]?.civ);if(chosen!==s.chosenCiv)migrated=true;s.chosenCiv=chosen;for(const p of players){const civ=currentCivKey(p.civ);if(civ!==p.civ)migrated=true;p.civ=civ}g.players=players;for(const e of g.entities||[]){e.civ=players[e.faction]?.civ||currentCivKey(e.civ);if(e.kind==='unit'&&!UNIT[e.type]){const mapped=LEGACY_UNIT_MAP[e.type];e.type=mapped&&UNIT[mapped]?mapped:'spear';migrated=true}if(e.kind==='building'){if(!Array.isArray(e.queue)){e.queue=[];migrated=true}for(const q of e.queue)if(!UNIT[q.type]){const mapped=LEGACY_UNIT_MAP[q.type];q.type=mapped&&UNIT[mapped]?mapped:'villager';migrated=true}}}if(migrated)rebuildSnapshotDerived(g,players);return s}
    function makeSnapshot(){if(!game)throw Error('目前沒有戰局');const entities=game.entities.filter(entity=>!entity.dead),liveIds=new Set(entities.map(entity=>entity.id)),{player:_player,enemy:_enemy,enemies:_enemies,ai:_ai,...state}=game;return{v:4,gameVersion:'4.0.0',projection:CURRENT_PROJECTION,savedAt:new Date().toISOString(),seed,nextId,chosenCiv,difficulty,playerCount:game.players.length,game:{...state,camera:{...game.camera,projection:CURRENT_PROJECTION},players:game.players,ais:game.ais,entities,nodes:game.nodes.filter(node=>!node.dead&&node.amount>0),selected:[...game.selected].filter(id=>liveIds.has(id)),fog:[...game.fog],particles:[],projectiles:[],markers:[],autoSaveIn:30}}}
    function validateSnapshot(s){
      if(!s||![1,2,3,4].includes(s.v)||!s.game)throw Error('不支援的存檔版本');const g=s.game,players=Array.isArray(g.players)?g.players:[g.player,g.enemy],count=players.filter(Boolean).length;
      if(!CIVS[s.chosenCiv]||!DIFF[s.difficulty])throw Error('文明或難度資料無效');
      if(!Array.isArray(g.entities)||!Array.isArray(g.nodes)||!Array.isArray(g.sites)||!Array.isArray(g.fog))throw Error('戰局資料不完整');
      if(g.entities.length>5000||g.nodes.length>5000||g.sites.length>16||g.fog.length!==MAP_W*MAP_H)throw Error('戰局資料尺寸異常');
      if(count<2||count>4)throw Error('玩家數量無效');const finite=n=>Number.isFinite(n),ids=new Set();for(const e of g.entities){if(!finite(e.id)||ids.has(e.id)||!Number.isInteger(e.faction)||e.faction<0||e.faction>=count||!finite(e.x)||!finite(e.y)||e.x<0||e.y<0||e.x>WORLD_W||e.y>WORLD_H||!finite(e.hp)||e.hp<0)throw Error('實體資料無效');if(e.kind==='unit'&&!UNIT[e.type])throw Error('未知兵種');if(e.kind==='building'&&(!BUILD[e.type]||!Array.isArray(e.queue)||e.queue.some(q=>!UNIT[q.type]||!finite(q.remaining)||!finite(q.total))))throw Error('未知建築或生產項目');if(!['unit','building'].includes(e.kind))throw Error('未知實體');ids.add(e.id)}
      for(const n of g.nodes)if(!finite(n.id)||!['food','wood','gold','stone'].includes(n.type)||!finite(n.x)||!finite(n.y)||!finite(n.amount))throw Error('資源資料無效');
      for(const p of players)if(!p||!CIVS[p.civ]||!p.res||Object.values(p.res).some(v=>!finite(v)||v<0)||!finite(p.age)||p.age<1||p.age>4)throw Error('玩家資料無效');
      return true
    }
    function persistGame(quiet=false){if(!game)return false;try{localStorage.setItem(SAVE_KEY,JSON.stringify(makeSnapshot()));localStorage.removeItem(V3_SAVE_KEY);localStorage.removeItem(V2_SAVE_KEY);localStorage.removeItem(LEGACY_SAVE_KEY);if(!quiet){tutorialEvent('saved');toast('戰局已保存，可在下次開啟時繼續。');Audio.sfx('age')}return true}catch{if(!quiet)toast('瀏覽器禁止本機儲存，請改用匯出存檔。');return false}}
    function restoreSnapshot(s,resume=false){
      s=migrateSnapshot(s);validateSnapshot(s);seed=s.seed|0;nextId=Math.max(1,s.nextId|0);chosenCiv=s.chosenCiv;difficulty=s.difficulty;game=s.game;if(!Array.isArray(game.players))game.players=[game.player,game.enemy];playerCount=game.players.length;game.playerCount=playerCount;game.difficulty=difficulty;game.player=game.players[0];game.enemy=game.players[1];game.enemies=game.players.slice(1);if(!Array.isArray(game.ais)){game.ais=Array(playerCount).fill(null);game.ais[1]=game.ai||{think:0,wave:DIFF[difficulty].wave,build:8,train:4}}for(let f=1;f<playerCount;f++)game.ais[f]=game.ais[f]||{think:0,wave:DIFF[difficulty].wave,build:8,train:4};game.ai=game.ais[1];game.supremacy=Array.from({length:playerCount},(_,i)=>game.supremacy?.[i]||0);game.wonder=Array.from({length:playerCount},(_,i)=>game.wonder?.[i]||0);for(const p of game.players)p.eliminated=!!p.eliminated;game.selected=new Set((game.selected||[]).filter(Number.isFinite));game.fog=new Uint8Array(game.fog);game.particles=[];game.projectiles=[];game.markers=[];game.autoSaveIn=30;game.minimapTimer=0;game.fogTimer=0;game.ended=false;game.running=true;game.paused=!resume;game.stats=game.stats||{gathered:0,trained:0,built:0};
      generateMap();if(game.camera?.projection!==CURRENT_PROJECTION){const old=game.camera||{},z=clamp(Number(old.zoom)||1,.62,1.65),town=game.entities.find(e=>!e.dead&&e.faction===0&&e.type==='town');game.camera={x:town?.x??WORLD_W/2,y:town?.y??WORLD_H/2,zoom:z,projection:CURRENT_PROJECTION}}for(const e of game.entities)e.selected=game.selected.has(e.id);dom.menu.classList.add('hidden');dom.game.classList.remove('hidden');$('#endOverlay').classList.add('hidden');$('#guideOverlay').classList.add('hidden');$('#pauseOverlay').classList.toggle('hidden',resume);resize();clampCamera();resetCameraInputAnchor();updateFog(true);updateHUD(true);renderTutorial();renderMenuState();Audio.init();Audio.ctx?.resume();last=performance.now();accumulator=0
    }
    function saveGame(){persistGame(false)}
    function loadGame(resume=false){try{const raw=storedSaveRaw();if(!raw){toast('尚未找到瀏覽器存檔。');return}const s=JSON.parse(raw);restoreSnapshot(s,resume);persistGame(true);toast(resume?'已接續上次戰局。':'已載入瀏覽器存檔。')}catch{toast('存檔已損毀或版本不相容。')}}
    function exportSave(){if(!game)return;try{persistGame(true);const data=JSON.stringify(makeSnapshot(),null,2),blob=new Blob([data],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a'),d=new Date(),stamp=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}-${String(d.getHours()).padStart(2,'0')}${String(d.getMinutes()).padStart(2,'0')}`;a.href=url;a.download=`帝國餘燼-存檔-${stamp}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200);tutorialEvent('exported');toast('可攜式存檔已匯出。');Audio.sfx('age')}catch{toast('匯出失敗，請稍後再試。')}}
    async function importSaveFile(file){try{if(!file||file.size>12*1024*1024)throw Error('檔案過大');const s=JSON.parse(await file.text());const resume=dom.game.classList.contains('hidden');restoreSnapshot(s,resume);persistGame(true);toast('存檔匯入成功，並已保存至此瀏覽器。');Audio.sfx('age')}catch{toast('無法匯入：請選擇有效的帝國餘燼 JSON 存檔。')}finally{$('#saveFileInput').value=''}}

    $('#civCards').addEventListener('click',e=>{const b=e.target.closest('[data-civ]');if(b){chosenCiv=b.dataset.civ;savePreferences();renderMenuState();Audio.init();Audio.sfx('select')}});
    document.querySelector('.match-options').addEventListener('click',e=>{const d=e.target.closest('[data-diff]'),p=e.target.closest('[data-players]');if(d)difficulty=d.dataset.diff;if(p)playerCount=Number(p.dataset.players);if(d||p){savePreferences();renderMenuState();Audio.init();Audio.sfx('click')}});
    const startTutorialGame=()=>{difficulty='休閒';playerCount=2;tutorialRequested=true;savePreferences();newGame();if(game?.tutorial?.active){enterTutorialStep(game.tutorial.step||0);renderTutorial()}};$('#startBtn').addEventListener('click',()=>{tutorialRequested=false;newGame()});$('#tutorialBtn').addEventListener('click',startTutorialGame);$('#continueBtn').addEventListener('click',()=>loadGame(true));$('#guideBtn').addEventListener('click',openGuide);$('#closeGuideBtn').addEventListener('click',closeGuide);$('#helpInGameBtn').addEventListener('click',openGuide);
    $('#pauseBtn').addEventListener('click',()=>togglePause(true));$('#resumeBtn').addEventListener('click',()=>togglePause(false));$('#abilityBtn').addEventListener('click',()=>usePower(0));
    $('#speedBtn').addEventListener('click',()=>{if(!game)return;game.speed=game.speed===1?2:game.speed===2?.5:1;updateHUD(true);Audio.sfx('click')});
    function fullscreenActive(){return!!(document.fullscreenElement||document.webkitFullscreenElement)}
    function updateFullscreenButton(){const b=$('#fullscreenBtn'),active=fullscreenActive();b.textContent=active?'離開全螢幕':'全螢幕';b.title=active?'離開全螢幕':'切換全螢幕'}
    async function toggleFullscreen(){try{if(fullscreenActive()){const exit=document.exitFullscreen||document.webkitExitFullscreen;if(!exit)throw Error('unsupported');const result=exit.call(document);if(result?.then)await result}else{const root=document.documentElement,enter=root.requestFullscreen||root.webkitRequestFullscreen;if(!enter)throw Error('unsupported');const result=enter.call(root);if(result?.then)await result}updateFullscreenButton();Audio.sfx('click')}catch{toast('瀏覽器目前無法切換全螢幕，請確認未封鎖此權限。')}}
    $('#fullscreenBtn').addEventListener('click',toggleFullscreen);document.addEventListener('fullscreenchange',()=>{updateFullscreenButton();resize()});document.addEventListener('webkitfullscreenchange',()=>{updateFullscreenButton();resize()});
    $('#muteBtn').addEventListener('click',()=>{Audio.init();Audio.toggle();savePreferences();updateHUD(true)});$('#volumeRange').addEventListener('input',e=>{Audio.setVolume(Number(e.target.value)/100);savePreferences()});
    $('#motionBtn').addEventListener('click',e=>{reducedMotion=!reducedMotion;e.target.textContent=reducedMotion?'精簡':'完整';savePreferences();toast(`動態效果已設為${e.target.textContent}。`)});
    const openSavePicker=()=>{$('#saveFileInput').value='';$('#saveFileInput').click()};$('#menuImportBtn').addEventListener('click',openSavePicker);$('#importBtn').addEventListener('click',openSavePicker);$('#saveFileInput').addEventListener('change',e=>importSaveFile(e.target.files?.[0]));
    const restartGame=()=>{const tutorial=!!game?.tutorial?.active;$('#pauseOverlay').classList.add('hidden');$('#endOverlay').classList.add('hidden');tutorial?startTutorialGame():(tutorialRequested=false,newGame())};$('#saveBtn').addEventListener('click',saveGame);$('#loadBtn').addEventListener('click',()=>loadGame(false));$('#exportBtn').addEventListener('click',exportSave);$('#restartBtn').addEventListener('click',restartGame);$('#menuBtn').addEventListener('click',returnMenu);$('#endRestartBtn').addEventListener('click',restartGame);$('#endMenuBtn').addEventListener('click',returnMenu);
    document.addEventListener('visibilitychange',()=>{if(document.hidden&&game&&!game.paused&&!game.ended)togglePause(true)});addEventListener('pagehide',()=>{if(game&&!game.ended)persistGame(true)});

    function frame(now){const real=Math.min(.1,(now-last)/1000||0);last=now;updateCamera(real);if(game&&!game.paused&&!game.ended){accumulator+=real*game.speed;let steps=0;while(accumulator>=STEP&&steps++<5){updateGame(STEP);accumulator-=STEP}}render(accumulator/STEP);raf=requestAnimationFrame(frame)}
    loadPreferences();$('#volumeRange').value=String(Math.round(Audio.volume*100));$('#motionBtn').textContent=reducedMotion?'精簡':'完整';updateFullscreenButton();renderMenuState();resize();requestAnimationFrame(frame);
