#nullable enable

using Microsoft.Xna.Framework;

namespace Empire.Game.Ui;

/// <summary>Stable action identifiers emitted by <see cref="GameUiRenderer"/>.</summary>
public enum UiActionId
{
    None,

    // Main menu setup.
    SelectCivilization,
    SelectDifficulty,
    SelectPlayerCount,
    StartGame,
    StartTutorial,
    ContinueGame,
    ImportSave,

    // Global game controls.
    TogglePauseMenu,
    ResumeGame,
    ToggleFullscreen,
    ToggleMute,
    CycleGameSpeed,
    UseCivilizationPower,

    // Commands and production.
    MoveOrder,
    AttackMoveOrder,
    StopOrder,
    SetRallyPoint,
    BuildBuilding,
    TrainUnit,
    ResearchTechnology,
    AdvanceAge,
    CancelQueueItem,
    PreviousCommandPage,
    NextCommandPage,
    NavigateMinimap,

    // Persistence and overlays.
    SaveGame,
    LoadGame,
    ExportSave,
    OpenGuide,
    CloseGuide,
    ReturnToMainMenu,
    ToggleTutorialPanel,
    ExitTutorial
}

/// <summary>
/// UI intent with optional stable data. Key carries civilization, difficulty,
/// unit, building or technology identifiers; Value carries player/page/queue indexes.
/// </summary>
public readonly record struct UiAction(UiActionId Id, string? Key = null, int Value = 0)
{
    public static readonly UiAction None = new(UiActionId.None);
}

/// <summary>A reusable immediate-mode hit target from the most recent layout pass.</summary>
public readonly record struct UiHitbox(Rectangle Bounds, UiAction Action, bool Enabled = true)
{
    public bool Contains(Point point) => Enabled && Bounds.Contains(point);
}

/// <summary>
/// Important rectangles generated by the most recent DrawMainMenu or DrawGameplay call.
/// The caller can use Minimap for pointer-to-world conversion without duplicating layout math.
/// </summary>
public readonly record struct UiLayoutSnapshot
{
    public Rectangle Viewport { get; init; }
    public Rectangle Header { get; init; }
    public Rectangle CivilizationGrid { get; init; }
    public Rectangle SetupPanel { get; init; }
    public Rectangle TopBar { get; init; }
    public Rectangle BottomBar { get; init; }
    public Rectangle SelectionPanel { get; init; }
    public Rectangle CommandPanel { get; init; }
    public Rectangle QueuePanel { get; init; }
    public Rectangle Minimap { get; init; }
    public Rectangle TutorialPanel { get; init; }
    public Rectangle Modal { get; init; }
}

/// <summary>Read-only values needed to render the native main menu.</summary>
public readonly record struct MainMenuUiState(
    string? Civilization,
    string? Difficulty,
    int PlayerCount,
    bool HasContinueGame);

/// <summary>Read-only presentation values kept outside the deterministic game state.</summary>
public readonly record struct GameplayUiState(
    bool IsFullscreen,
    bool IsMuted,
    bool PauseMenuOpen,
    bool GuideOpen,
    bool CanLoadGame,
    int CommandPage,
    bool TutorialCollapsed,
    string? Notice,
    float NoticeRemainingSeconds);
